[site]
title = "Red Hat Arcade"
description = """
Welcome to the Red Hat Arcade, brought to you by the Gaming Community of Practice.

The arcade features a collection of open-source games created by Red Hatters.
All games are free to play, and were built with open-source tools.

The game isn't over when you're done playing. Your contributions of art, code, music, and ideas can shape the future of the games. Just click the Contribute link beside your favorite game to get started.

All games run on OpenShift sponsored by <a rel="noopener" href="https://www.osci.io/">OSCI</a>.
"""
collection_name = "Open-Source Games Collection"
warhw_login = """
<pfe-button arcade-action="login" size="large">
    <button>Red Hat Associate Login</button>
</pfe-button>
Are you a Red Hat Associate?   Log in to participate in WARHW!
"""
warhw_logged_in = """
<pfe-icon icon="web-check" size="md" style="--pfe-icon--color: green"></pfe-icon> You're logged in as <span id="warhw-login-id"></span>!
<pfe-button arcade-action="logout" variant="secondary">
    <button>Logout</button>
</pfe-button>
"""

[games.stonehold]
title = "Stonehold"
play = "https://arcade.redhat.com/stonehold"
contribute = "https://github.com/ScriptaGames/Stonehold"
thumb = "./stonehold_thumb.png"
leaderboard = true
leaderboard_route = "/stonehold-leaderboard"
description = """
You're a dwarf that has been imprisoned and must escape Stonehold! See how far you can get in this dungon!
"""

[games.podescape]
title = "Pod Escape"
play = "/pod-escape/"
contribute = "https://github.com/CodeCafeOpenShiftGame/PodEscape"
thumb = "./pod-escape.png"
leaderboard = true
leaderboard_route = "/pod-escape-leaderboard"
description = """
Your project is being deleted&mdash;help a pod escape from a disappearing digital landscape. Built by a
team of Red Hatters passionate about gaming and Kubernetes.
"""

[games.pae]
title = "Pity About Earth..."
play = "/pity-about-earth/"
contribute = "https://github.com/ScriptaGames/pityaboutearth"
thumb = "./pityaboutearth.jpg"
leaderboard = true
leaderboard_route = "/pity-about-earth-leaderboard"
description = """
<figure>
<blockquote>
    Humanity, I am sick of you. #2020
    <br> <br>
    Yours truly,
</blockquote>
<figcaption>the Universe</figcaption>
</figure>
"""

[games.bash]
title = "Command Line Heroes: BASH"
play = "/bash/"
contribute = "https://github.com/CommandLineHeroes/clh-bash"
thumb = "./bash.jpg"
description = """
How many commands can you type in 60 seconds? Set the terminal on fire in this memory game.
Created in collaboration with <a rel="noopener" target="_blank" href="https://www.redhat.com/en/command-line-heroes">Command Line Heroes</a>.
"""

[games.zorbio]
title = "Zorbio"
play = "https://zorb.io"
contribute = "https://github.com/ScriptaGames/zorbio"
thumb = "./zorbio.jpg"
description = """
Fly a sphere through a 3D world, consuming food and other spheres, to get the high score in this multiplayer game!
"""

[games.sqoff]
title = "Square Off"
play = "http://sqoff.com"
contribute = "https://github.com/ScriptaGames/SquareOff/"
thumb = "./square-off.png"
description = """
Square Off is a multiplayer air hockey game, where you place squares on a grid to bounce the puck.  Protect your goal!
"""

[games.shipwars]
title = "Shipwars"
play = "/shipwars/"
contribute = "https://github.com/redhat-gamedev?q=shipwars&type=&language=&sort="
thumb = "./shipwars.png"
description = """
If you have ever wanted to yell out "You sank my battleship", this is your opportunity. Place your ships
on a grid, hoping to avoid the attacks of your AI opponent, while also placing your shots in an effort
to destroy all of your opponents ships before they sink yours!
"""

[games.subhunt]
title = "Sub Hunt"
play = "http://subhunt.fun"
contribute = "https://github.com/ScriptaGames/sub-hunt"
thumb = "./subhunt_thumb.png"
description = """
In 1641, the Merchant Royal sunk. It was carrying more than 100,000 pounds of gold and silver, and it’s location has never been known… until now.
You have Narrowed down the shipwrecks’s location and you’re ready to.. Hunt for the Merchant Royal! Made in one weekend by Red Hatters for Ludum Dare, theme: Deeper and Deeper.
"""

[games.fourfold]
title = "FOURFOLD"
play = "https://arcade.redhat.com/fourfold"
contribute = "https://github.com/rottencandy/js13k2020"
thumb = "./fourfold.png"
description = """
Navigate your way through this mind-bending puzzle game.  Developed by Red Hatter Mohammed Saud for the 2020 JS13K game jam.  The whole game is less than 13kb!

Controls:
Move - WASD or Arrows keys\n
"""
